// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMF4m-0-I57xFb55mOXHUbSa8moo8bdx4',
    appId: '1:867427851590:web:4ed9d5a40dd1358e929947',
    messagingSenderId: '867427851590',
    projectId: 'ridesafe-940e6',
    authDomain: 'ridesafe-940e6.firebaseapp.com',
    storageBucket: 'ridesafe-940e6.firebasestorage.app',
    measurementId: 'G-5GRX2W3SX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1FNZymZppKhOxgx3Sh1knoK55bO-E-g',
    appId: '1:867427851590:android:91bd2932853f49bf929947',
    messagingSenderId: '867427851590',
    projectId: 'ridesafe-940e6',
    storageBucket: 'ridesafe-940e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn8NA4cUdkcUTdNdT3M68Bhg2UkrTW6I0',
    appId: '1:867427851590:ios:9cbc74071fce1fee929947',
    messagingSenderId: '867427851590',
    projectId: 'ridesafe-940e6',
    storageBucket: 'ridesafe-940e6.firebasestorage.app',
    iosBundleId: 'com.example.rideSafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn8NA4cUdkcUTdNdT3M68Bhg2UkrTW6I0',
    appId: '1:867427851590:ios:9cbc74071fce1fee929947',
    messagingSenderId: '867427851590',
    projectId: 'ridesafe-940e6',
    storageBucket: 'ridesafe-940e6.firebasestorage.app',
    iosBundleId: 'com.example.rideSafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMF4m-0-I57xFb55mOXHUbSa8moo8bdx4',
    appId: '1:867427851590:web:2d884694326eaaad929947',
    messagingSenderId: '867427851590',
    projectId: 'ridesafe-940e6',
    authDomain: 'ridesafe-940e6.firebaseapp.com',
    storageBucket: 'ridesafe-940e6.firebasestorage.app',
    measurementId: 'G-ECVY5BBHH5',
  );
}
